api:
  id: "19593584"
  
platform:
  client_id: "![0FHei9kXx+sOncppCCnotURcr2pEXs5i9gsAP6geJXsXa+YhXG75YA==]"
  client_secret: "![nhRSoSXeHsts94ntwvwqX57sy9udGLI5KGK1JJtzKIuaqLblPhyBNw==]"

salesforce:
  username: "![apdaccU5e2OyLxHyyxfy3HAT/HjdNJqA/OV0VmPIq+A=]"
  password: "![EtT5KLlB/f1VaJzAvdO79w==]"
  token: "![c6q6Kt5m/QoBY6baozrHwfLcnZXr8csLSvOS7i6jYnA=]"