name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - sample
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
 
      - name: Build project
        run: mvn clean package
 
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to Dev
        env:
          USERNAME: ${{ secrets.anypoint_platform_username }}
          PASSWORD: ${{ secrets.anypoint_platform_password }}
        run: |
          mvn deploy:deploy-file -Denv=dev -Dfile=target/your-mule-app.jar
 
  deploy-qa:
    if: github.ref == 'refs/heads/main'
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to QA
        env:
          USERNAME: ${{ secrets.anypoint_platform_username }}
          PASSWORD: ${{ secrets.anypoint_platform_password }}
        run: |
          mvn deploy:deploy-file -Denv=qa -Dfile=target/your-mule-app.jar
 
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to Production
        env:
          USERNAME: ${{ secrets.anypoint_platform_username }}
          PASSWORD: ${{ secrets.anypoint_platform_password }}
        run: |
          mvn deploy:deploy-file -Denv=prod -Dfile=target/your-mule-app.jar
