name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  call-workflow:
    uses: GayathriNuthalapati/algolia-api/.github/workflows/mule-deploy-workflow.yml@test
    secrets:
      username: ${{ secrets.connected_app_client_id }}
      password: ${{ secrets.connected_app_client_secret}}
