name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  call-workflow:
    uses: .github/workflows/mule-deploy-workflow.yml@test
