name: Mule MUnit CI

on:
  push:
    branches:
      - ch2-munit-test2
  pull_request:
    branches:
      - ch2-munit-test2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    - name: Run MUnit tests
      run: mvn clean test

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports
