name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  call-workflow:
    uses: GayathriNuthalapati/algolia-api/.github/workflows/mule-deploy-workflow.yml@test
    secrets: inherit
