name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - demo
  pull_request:
    branches:
      - demo

jobs:
  call-workflow:
    uses: GayathriNuthalapati/algolia-api/.github/workflows/reusableWorkflow.yml@dev
    secrets: inherit
