name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - postman-test-coverag
  pull_request:
    branches:
      - postman-test-coverag


jobs:
  call-workflow:
    uses: GayathriNuthalapati/algolia-api/.github/workflows/reusableWorkflow.yml@postman-test-coverage
    secrets: inherit
