name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod


jobs:
  call-workflow:
    uses: GayathriNuthalapati/algolia-api/.github/workflows/reusableWorkflow.yml@prod
    secrets: inherit
